{
  "name": "omarchy",
  "vars": {
    "background": "{{ background }}",
    "foreground": "{{ foreground }}",
    "accent": "{{ accent }}",
    "selectedBackground": "{{ mix background accent 22% }}",
    "color0": "{{ color0 }}",
    "color1": "{{ color1 }}",
    "color2": "{{ color2 }}",
    "color3": "{{ color3 }}",
    "color4": "{{ color4 }}",
    "color5": "{{ color5 }}",
    "color6": "{{ color6 }}",
    "color7": "{{ color7 }}",
    "color8": "{{ color8 }}",
    "color9": "{{ color9 }}",
    "color10": "{{ color10 }}",
    "color11": "{{ color11 }}",
    "color12": "{{ color12 }}",
    "color13": "{{ color13 }}",
    "color14": "{{ color14 }}",
    "color15": "{{ color15 }}",
    "orange": "{{ orange }}",
    "chrome": "{{ dark_background }}",
    "panel": "{{ mix background foreground 6% }}",
    "panelAlt": "{{ mix background foreground 10% }}",
    "panelPending": "{{ mix background accent 12% }}",
    "panelSuccess": "{{ mix background green 12% }}",
    "panelError": "{{ mix background red 12% }}",
    "border": "{{ mix background foreground 30% }}",
    "borderMuted": "{{ mix background foreground 20% }}",
    "mutedText": "{{ mix foreground background 34% }}",
    "dimText": "{{ mix foreground background 52% }}"
  },
  "colors": {
    "accent": "accent",
    "border": "border",
    "borderAccent": "accent",
    "borderMuted": "borderMuted",
    "success": "color2",
    "error": "color1",
    "warning": "color3",
    "muted": "mutedText",
    "dim": "dimText",
    "text": "foreground",
    "thinkingText": "dimText",
    "selectedBg": "selectedBackground",
    "userMessageBg": "panel",
    "userMessageText": "foreground",
    "customMessageBg": "panel",
    "customMessageText": "foreground",
    "customMessageLabel": "accent",
    "toolPendingBg": "panelPending",
    "toolSuccessBg": "panelSuccess",
    "toolErrorBg": "panelError",
    "toolTitle": "accent",
    "toolOutput": "foreground",
    "mdHeading": "color5",
    "mdLink": "accent",
    "mdLinkUrl": "color6",
    "mdCode": "color6",
    "mdCodeBlock": "foreground",
    "mdCodeBlockBorder": "borderMuted",
    "mdQuote": "mutedText",
    "mdQuoteBorder": "borderMuted",
    "mdHr": "borderMuted",
    "mdListBullet": "color5",
    "toolDiffAdded": "color2",
    "toolDiffRemoved": "color1",
    "toolDiffContext": "mutedText",
    "link": "accent",
    "syntaxComment": "dimText",
    "syntaxKeyword": "color5",
    "syntaxFunction": "color4",
    "syntaxVariable": "accent",
    "syntaxString": "color2",
    "syntaxNumber": "color3",
    "syntaxType": "color4",
    "syntaxOperator": "color5",
    "syntaxPunctuation": "mutedText",
    "thinkingOff": "borderMuted",
    "thinkingMinimal": "dimText",
    "thinkingLow": "color4",
    "thinkingMedium": "color5",
    "thinkingHigh": "accent",
    "thinkingXhigh": "color1",
    "thinkingMax": "color3",
    "bashMode": "color3",
    "pythonMode": "color6",
    "statusLineBg": "chrome",
    "statusLineSep": "borderMuted",
    "statusLineModel": "accent",
    "statusLinePath": "color6",
    "statusLineGitClean": "color2",
    "statusLineGitDirty": "color3",
    "statusLineContext": "mutedText",
    "statusLineSpend": "color6",
    "statusLineStaged": "color2",
    "statusLineDirty": "color3",
    "statusLineUntracked": "color4",
    "statusLineOutput": "color5",
    "statusLineCost": "orange",
    "statusLineSubagents": "accent"
  },
  "export": {
    "pageBg": "background",
    "cardBg": "panel",
    "infoBg": "panelAlt"
  },
  "terminal": {
    "background": "background",
    "foreground": "foreground",
    "chrome": "chrome",
    "widget": "panelAlt",
    "ansi": [
      "color0",
      "color1",
      "color2",
      "color3",
      "color4",
      "color5",
      "color6",
      "color7",
      "color8",
      "color9",
      "color10",
      "color11",
      "color12",
      "color13",
      "color14",
      "color15"
    ]
  }
}
